### ISSUE TITLE
DeprecationWarning regarding use of distutils Version classes

### ISSUE THREAD

**Issue by prsangappa** [joanvila/aioredlock#109]
```
ERROR    aioredlock.redis:redis.py:218 Can not set lock "u:" on <Instance(connection='redis://:*******@127.0.0.1:6379'>
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/aioredlock/redis.py", line 195, in set_lock
    with await self.connect() as redis:
  File "/venv/lib/python3.9/site-packages/aioredlock/redis.py", line 166, in connect
    self._pool = await self._create_redis_pool(address, **redis_kwargs)
  File "/venv/lib/python3.9/site-packages/aioredlock/redis.py", line 113, in _create_redis_pool
    if StrictVersion(aioredis.__version__) >= StrictVersion('1.0.0'):  # pragma no cover
  File "/venv/lib/python3.9/site-packages/setuptools/_distutils/version.py", line 55, in __init__
    warnings.warn(
DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

```

**Comment by nikto-b** [comment]
Looks like that deprecation warning turned into an error in `3.12` ([changelog](https://docs.python.org/3/whatsnew/3.12.html))
